module:
  mounts:
    - source: assets
      target: assets
    - source: content
      target: content
    - source: data
      target: data

permalinks:
  page:
    expertises: /competences/:slug/
    posts: /journal/:year-:month-:day-:slug/
  section:
    expertises: /competences/
    posts: /journal/
  taxonomy:
    categories: /journal/categories/
    posts_expertises: /journal/expertises/
    tags: /journal/tags/
  term:
    categories: /journal/categories/:slug/
    posts_expertises: /journal/expertises/:slug/
    tags: /journal/tags/:slug/

params:
  _merge: deep
  expertises:
    _merge: deep
    thumbnail:
      _merge: deep
      desktop: '636x273'
